add base scrapper for budget
CivicDataLab/hp-fiscal-data-explorer-backend pull request #20
Opened 2019-07-01 08:57 UTC by shreyaagrawal0809

2019-07-01 09:19 UTC, curioswati reviewed
please remove the `datasets` dir, specifically the `*ddo_codes` files from the PR as there's already an issue #8 open for this.

2019-07-01 10:23 UTC, shreyaagrawal0809 commented
Deleted please checkonce

2019-08-13 10:43 UTC, curioswati requested changes

2019-08-13 10:43 UTC, curioswati commented on scraper/scraper/spiders/budget_base.py
> +        pdb.set_trace()
remove pdb call

2019-08-13 10:43 UTC, curioswati commented on scraper/scraper/spiders/budget_base_pdf.py
> +
please remove these extra lines at the end of file

2019-08-13 10:43 UTC, curioswati commented on scraper/scraper/spiders/budget_base_pdf.py
> + #   def save_pdf_receipts(self, response):
can we get rid of this function

2019-10-11 06:29 UTC, curioswati requested changes

2019-10-11 06:29 UTC, curioswati commented on scraper/scraper/spiders/budget_base.py
> +                self.query_url.format(urlencode(query_params)), # pylint: disable=no-member
can we not disable this and resolve?

2019-10-11 06:29 UTC, curioswati commented on scraper/scraper/spiders/budget_base.py
> +                    'query_name': self.query_name,  #pylint: disable=no-member
can we get rid of these `disable=no-member`

2019-10-11 06:29 UTC, curioswati commented on scraper/scraper/spiders/budget_base.py
> +    def parse_dataset(self, response):  #pylint: disable=no-self-use
you need not disable this, let the error show in pylint.

2019-10-11 06:29 UTC, curioswati commented on scraper/scraper/spiders/budget_exp_receipts.py
> +    unit = '.00001'
fix this new line error

2019-10-11 10:39 UTC, curioswati approved these changes
good work!

2019-10-11 10:39 UTC, merged