WIP: Fix #24 setup process manager with apache airflow
CivicDataLab/hp-fiscal-data-explorer-backend pull request #25
Opened 2019-08-19 09:51 UTC by curioswati

2019-08-28 12:04 UTC, apoorv74 commented
hey @curioswati did you try running this for a sample ? also, can you share the link to the airflow dashboard, we can use that for reporting logs and other metrics

2019-09-05 10:52 UTC, curioswati commented
> hey @curioswati did you try running this for a sample ? also, can you share the link to the airflow dashboard, we can use that for reporting logs and other metrics

Yes @apoorv74. The sample run is in progress and the dashboard is live.

2019-10-10 10:30 UTC, gggodhwani requested changes
Requesting some minor changes

2019-10-10 10:30 UTC, gggodhwani commented on scheduler/tasks/crawl_treasuries.py
> +    'start_date': dt.datetime(2019, 8, 1),
Can we please set it to the first of the month whenever the call happen?

2019-10-10 10:30 UTC, gggodhwani commented on scheduler/tasks/crawl_treasuries.py
> +    'retries': 0
Can we explain the reason of keeping the retry count keeping 0?

2019-10-10 10:30 UTC, gggodhwani commented on scheduler/tasks/crawl_treasuries.py
> +         schedule_interval='30 4 * * *',
Can we explain the CRON equivalent & timezone?

2019-10-10 10:30 UTC, gggodhwani commented on scheduler/tasks/crawl_treasuries.py
> +        cd $project_path/scraper && scrapy crawl treasury_expenditures -a start={{ ds_nodash }} -a end={{ ds_nodash }}
Can we please link the Airflow docs here to explain Jinja variables if any?

2019-10-10 10:30 UTC, gggodhwani commented on scheduler/tasks/crawl_treasuries.py
> +    CRAWL_EXPENDITURE = BashOperator(
Can we make the nomenclature consistent, something like: EXP_CRAWL_TASK

2019-10-10 10:30 UTC, gggodhwani commented on scheduler/tasks/crawl_treasuries.py
> +    CRAWL_RECEIPTS = BashOperator(
Same nomenclature thing

2019-10-10 10:30 UTC, gggodhwani commented on scraper/scraper/spiders/treasury_base.py
> +            time.sleep(5)
Comment: # add a sleep of 5 seconds after each treasury crawled

2019-10-11 06:18 UTC, gggodhwani approved these changes
:+1:

2019-10-11 06:31 UTC, merged