add spider for budget receipts data
CivicDataLab/hp-fiscal-data-explorer-backend pull request #46
Opened 2019-11-04 13:09 UTC by curioswati

2019-11-15 18:00 UTC, curioswati commented
please only review till the commit: `e419cf8`, the latest is just a rebase from another branch.

2019-11-18 13:49 UTC, gggodhwani requested changes

2019-11-18 13:49 UTC, gggodhwani commented on scraper/scraper/spiders/budget_base.py
> +        filepath = os.path.join(BUDGET_DATA_PATH, self.name.split('_')[-1], filename)
Make the filepath name much more verbose

2019-11-18 13:49 UTC, gggodhwani commented on scraper/scraper/spiders/budget_base.py
> +        if not re.match(r'\d{2}/\d{2}/\d{4}', self.date):
Make a variable for date regex

2019-11-18 13:49 UTC, gggodhwani commented on scraper/scraper/spiders/budget_base.py
> +        crawler.signals.connect(spider.spider_closed, signal=signals.spider_closed)  #pylint: disable=no-member
Add reference to small guideline/doc on Scrapy signals

2019-11-18 13:49 UTC, gggodhwani commented on scraper/scraper/spiders/budget_base.py
> +                    'major_code': '0000',  # we use all major heads
0000 is code for "All Major Heads"

2019-11-18 13:49 UTC, gggodhwani commented on scraper/scraper/spiders/budget_exp_receipts.py
> +    unit = '.00001'
Just check if the unit, and local minima. Plus rename to explain the decimals

2019-11-26 10:11 UTC, gggodhwani approved these changes
:+1:

2019-11-26 11:05 UTC, merged